language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
  - make deps

script:
  - make gometalinter
  - make test
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
